### ISSUE TITLE
Grid view not working as it should 

### ISSUE THREAD

**Issue by veronicahorgan** [rstudio/connectwidgets#74] opened 2022-08-12 11:33 UTC
Hi, I am creating a "landing page" for connect content and am having issues with the grid view. The first issue I had (as per issue #72) was that each content card was huge and much bigger than the rsc_card cards themselves. It was not putting them in grid view. I then went into the function and have commented out: 

`# dependencies[["rsc_grid-theme"]]  <- resolve_theme_dependency(("rsc_grid")`

which seems to have solved the issue to a certain extent - I now have normal sized thumbnails but only three per row, as opposed to four. So the margins aren't aligning with the rest of the page. 

I have tried to play around with the src code but am confused as I can see that each card should be 22.75% width so it should fit four.

**Comment by edavidaja** [comment] 2022-09-08 19:07
duplicate of #72

**Closed by edavidaja** 2022-09-08 19:07 UTC
